"""Configurable thresholds for Phase 6 feature selection."""

from __future__ import annotations

NEAR_CONSTANT_THRESHOLD = 0.99
MODERATE_MISSING_THRESHOLD = 0.20
HIGH_MISSING_THRESHOLD = 0.50
HIGH_CARDINALITY_THRESHOLD = 0.50
CORRELATION_THRESHOLD = 0.90
VIF_THRESHOLD = 10.0
VIF_REVIEW_THRESHOLD = 5.0
PREVIEW_ROWS = 5
MAX_VIF_FEATURES = 40
MIN_ROWS_FOR_MI = 10
MIN_ROWS_FOR_VIF = 20
MI_RANDOM_STATE = 42
